project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!labs/lab05.qmd"
    - "!labs/lab06.qmd"
    - "!labs/lab07.qmd"
    - "!labs/lab08.qmd"
    - "!labs/lab09.qmd"

website:
  title: "Βιοστατιστική – Εργαστήρια"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs/lab01.qmd
        text: Lab 1
      - href: labs/lab02.qmd
        text: Lab 2
      - href: labs/lab03.qmd
        text: Lab 3
      - href: labs/lab04.qmd
        text: Lab 4
      - href: labs/lab05.qmd
        text: Lab 5
      - href: labs/lab06.qmd
        text: Lab 6
      - href: labs/lab07.qmd
        text: Lab 7
      - href: labs/lab08.qmd
        text: Lab 8
      - href: labs/lab09.qmd
        text: Lab 9

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
